version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins_build
      dockerfile: Dockerfile.final
    container_name: jenkins-blueocean
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
      - "3000:3000" # Porta para a aplicação React
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - $HOME:/home
    environment:
      - DOCKER_TLS_VERIFY=0
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    restart: always
    networks:
      - jenkins

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  jenkins:
    name: jenkins
