version: '3.8'

services:
  jenkins-blueocean:
    build:
      context: ./jenkins_build
    container_name: jenkins-blueocean
    user: root # Necessário para interagir com o socket do Docker no macOS
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # No macOS, o Docker Desktop mapeia o socket para este caminho padrão
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - $HOME:/home
    restart: always
    environment:
      - DOCKER_TLS_VERIFY=0
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    networks:
      - jenkins

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  jenkins:
    name: jenkins
